application: pcwapp
version: use-version-arg
runtime: python27
api_version: 1
threadsafe: false

default_expiration: 7d

handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)

- url: /static
  static_dir: static

- url: /.*
  script: pcwapp.application

libraries:
- name: django
  version: latest
